### ISSUE TITLE
Design doc: Able to reply to a message

### ISSUE THREAD

**Issue by khankuan** [GustavoMeza/CodeU-Summer-2018#22]
More details can be found here: https://sites.google.com/codeustudents.com/summer2018/projects/open-project/replies

**Comment by GustavoMeza** [comment]
Doc can be found here: https://docs.google.com/document/d/1z8UQ_m20C_yB5FnIetU01xC0w8yiDFbgJeOXT0N--JA/edit#heading=h.iofiey6zqqo8
