### ISSUE TITLE
Link to chat page from user's sent messages under Profile page

### ISSUE THREAD

**Issue by khankuan** [GustavoMeza/CodeU-Summer-2018#25]
Adding a link helps whoever that is reading the profile user's messages to quickly enter the chat page and see all the messages in that chat.

**Comment by khankuan** [comment]
@Dnae-ferguson sorry this ticket was confusing. This is not part of your current task but an enhancement from the profile page (after your current task is done). Also, this ticket is just an idea, we may/may not work on it depending on what we discuss in the next meeting :)

**Comment by GustavoMeza** [comment]
You can reuse the activity-helper.jsp code!
And it's actually something useful to do. If someday we decide to change the UI we'll only have to change it once!
The cons are that you need to pass the Activity, so we'll need something like GetActivity(Message) on ActivityStore, or maybe we can add the activity id as a Message property, or we can change activity-helper to receive the message instead.
Think about it!
